### ISSUE TITLE
AElf Oracle Related Contracts TODO LIST

### ISSUE THREAD

**Issue by EanCuznaivy** [PortAllProject/port-all-contracts#1]
**Oracle Contract**

- [x] Basic pipeline: Query, Commit, Reveal, CancelQuery
- [x] Management related methods: ChangeController, SetThreshold

**Report Contract**

- [x] Using Oracle Contract: QueryOracle, CancelQueryOracle
- [x] Generate Report for viewing: ProposeReport, ConfirmReport, GetReport
- [ ] Observer management: ApplyObserver, QuitObserver, MortgageTokens, WithdrawTokens
- [ ] Generate Report for transmitting to ethereum: GetRawReport

**ACS13 Related Stuff**

- [x] Interfaces definations
- [x] Demo contract
- [x] Pipeline tests

Currently working at:
- Observer management
